#!/usr/bin/env python3
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'tools'))
from freev_registry import load_registry,script_safe_json
reg=load_registry();apps=reg['apps']
labels={a['id']:a['label'] for a in apps}; anim={a['id']:a['animation'] for a in apps}; layers={a['id']:a['animationLayers'] for a in apps}
cover={a['id']:True for a in apps if a.get('animationCover')}; reconstruct=[a['id'] for a in apps if a.get('reconstructAnimationSymbol')]
module='// AUTO-GENERATED by tools/generate_registry.py — DO NOT EDIT\n'
module+=f'export const LABELS={script_safe_json(labels,separators=(",",":"),ensure_ascii=False)};\n'
module+=f'export const DEFAULT_ANIM={json.dumps(anim,separators=(",",":"))};\n'
module+=f'export const ANIM_LAYERS={json.dumps(layers,separators=(",",":"))};\n'
module+=f'export const ANIM_COVER={json.dumps(cover,separators=(",",":"))};\n'
module+=f'export const RECONSTRUCT_SYMBOL=new Set({json.dumps(reconstruct)});\n'
module+=f'export const DEFAULT_APP={json.dumps(reg["defaultApp"])};\n'
module+=f'export const APP_REGISTRY={script_safe_json(apps,separators=(",",":"),ensure_ascii=False)};\n'
(ROOT/'web/generated-apps.js').write_text(module,encoding='utf-8')
# Types: only replace the generated app union line.
tp=ROOT/'types/freev-icon.d.ts'; text=tp.read_text(encoding='utf-8')
union='|'.join(json.dumps(a['id']) for a in apps)
lines=text.splitlines();lines[0]=f'export type FreevApp={union};';tp.write_text('\n'.join(lines)+'\n',encoding='utf-8')
# Demo list generated and inline demo kept synchronized.
demo=[{'id':a['id'],'label':a['label'],'kind':a['kind']} for a in apps]
(ROOT/'web/apps.json').write_text(json.dumps(demo,indent=2,ensure_ascii=False),encoding='utf-8')
ip=ROOT/'web/index.html'
if ip.exists():
 import re
 it=ip.read_text(encoding='utf-8')
 safe_demo=script_safe_json(demo,separators=(",",":"),ensure_ascii=False)
 it=re.sub(r'const apps=\[.*?\];function r\(\)', lambda _match:'const apps='+safe_demo+';function r()', it, count=1)
 ip.write_text(it,encoding='utf-8')
# Keep docs manifest apps synchronized.
mp=ROOT/'docs/manifest.json'; m=json.loads(mp.read_text(encoding='utf-8'));m['apps']={a['id']:{'label':a['label'],'animation':a['animation'],'kind':a['kind']} for a in apps};m['automaticOnboarding']={'registry':'registry/apps.json','incoming':'incoming/','command':'python tools/icon_pipeline.py sync --enforce','buildGate':True};mp.write_text(json.dumps(m,indent=2,ensure_ascii=False),encoding='utf-8')
print(f'Generated registry for {len(apps)} FREEV apps')
