import {LABELS,DEFAULT_ANIM,ANIM_LAYERS,ANIM_COVER,RECONSTRUCT_SYMBOL,DEFAULT_APP,APP_REGISTRY} from './generated-apps.js';
const THEMES={"cyan":["#062B8C","#11D7FF"],"purple":["#2C0D91","#C84DFF"],"emerald":["#045C4A","#23E1A7"],"gold":["#7A5400","#FFD23B"],"ruby":["#7C0F1B","#FF4B5C"],"rose":["#86115D","#FF4FCB"],"orange":["#92300A","#FF8A2A"],"graphite":["#172131","#6E86A4"],"ice":["#54789B","#D9F3FF"]};
const BADGE={none:"",new:"N",update:"MAJ",beta:"β",pro:"PRO",notification:"",download:"↓"};
const APPS=new Set(Object.keys(LABELS));
const THEMES_SET=new Set(Object.keys(THEMES));
const MODES=new Set(['auto','light','dark']);
const STATES=new Set(['default','hover','active','disabled','loading']);
const BADGES=new Set(Object.keys(BADGE));
const ANIMATIONS=new Set(['none','auto',...Object.values(DEFAULT_ANIM)]);
const MOTIONS=new Set(['auto','on','off']);
const imageCache=new Map(),renderCache=new Map();let renderCacheBytes=0;const DEFAULT_CACHE_BYTES=48*1024*1024;
const rgb=h=>[0,2,4].map(i=>parseInt(h.replace('#','').slice(i,i+2),16)/255);
function finiteConfig(value,fallback,min,max){try{const n=Number(value);return Number.isFinite(n)&&n>0?Math.max(min,Math.min(max,n)):fallback}catch{return fallback}}
function maxCacheBytes(){return finiteConfig(globalThis.FREEV_ICON_CACHE_MB,48,8,256)*1024*1024}
function maxRenderSide(){return Math.round(finiteConfig(globalThis.FREEV_ICON_MAX_RENDER_SIDE,1024,64,2048))}
function deviceScale(){return finiteConfig(globalThis.devicePixelRatio,1,.5,2)}
function cacheSet(k,canvas){const bytes=canvas.width*canvas.height*4;if(bytes>maxCacheBytes())return;const prior=renderCache.get(k);if(prior){renderCacheBytes-=prior.bytes;renderCache.delete(k)}while(renderCache.size&&renderCacheBytes+bytes>maxCacheBytes()){const [old,v]=renderCache.entries().next().value;renderCache.delete(old);renderCacheBytes-=v.bytes}renderCache.set(k,{canvas,bytes});renderCacheBytes+=bytes}
function clearFreevIconCaches(){imageCache.clear();renderCache.clear();renderCacheBytes=0}
function getFreevIconCacheStats(){return{images:imageCache.size,renders:renderCache.size,renderBytes:renderCacheBytes,maxBytes:maxCacheBytes()}}
async function loadImage(url){if(imageCache.has(url))return imageCache.get(url);let p;p=new Promise((res,rej)=>{const im=new Image();im.decoding='async';try{const u=new URL(url,document.baseURI);if(u.origin!==location.origin)im.crossOrigin='anonymous'}catch{}im.onload=()=>res(im);im.onerror=()=>rej(new Error(`FREEV icon asset failed to load: ${url}`));im.src=url}).catch(error=>{if(imageCache.get(url)===p)imageCache.delete(url);throw error});imageCache.set(url,p);return p}
function recolor(data,theme){const [dh,lh]=THEMES[theme]||THEMES.cyan,d=rgb(dh),l=rgb(lh),p=data.data;for(let i=0;i<p.length;i+=4){const r=p[i]/255,g=p[i+1]/255,b=p[i+2]/255,a=p[i+3]/255;if(!a)continue;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx>1e-6?(mx-mn)/mx:0,lum=.2126*r+.7152*g+.0722*b;if(sat<.14&&lum>.68)continue;if(sat<.08&&lum<=.68){const q=d.map((v,j)=>v*.88+l[j]*.12);p[i]=(r*.82+q[0]*.18)*255;p[i+1]=(g*.82+q[1]*.18)*255;p[i+2]=(b*.82+q[2]*.18)*255;continue}let x=Math.max(0,Math.min(1,(lum-.05)/.95));x=Math.pow(x,.90);p[i]=(d[0]*(1-x)+l[0]*x)*255;p[i+1]=(d[1]*(1-x)+l[1]*x)*255;p[i+2]=(d[2]*(1-x)+l[2]*x)*255}return data}
function moduleBase(){return new URL('../',import.meta.url)}
function emitError(el,app,error){queueMicrotask(()=>el.dispatchEvent(new CustomEvent('freev-icon-error',{bubbles:true,composed:true,detail:{app,error}})))}
function assetUrl(el,rel,app=DEFAULT_APP){const custom=el.getAttribute('asset-base')||globalThis.FREEV_ICON_ASSET_BASE;try{if(custom){const base=new URL(String(custom),document.baseURI);if(!['http:','https:','file:'].includes(base.protocol))throw new Error(`Unsupported protocol: ${base.protocol}`);return new URL(rel,base).href}return new URL(rel,moduleBase()).href}catch(error){emitError(el,app,new Error(`Invalid FREEV asset base: ${String(custom)}`));return new URL(rel,moduleBase()).href}}
function effectiveApp(el){const raw=el.getAttribute('app')||DEFAULT_APP;if(APPS.has(raw))return raw;emitError(el,raw,new Error(`Unknown FREEV app: ${raw}`));return DEFAULT_APP}
function effectiveTheme(el){const t=el.getAttribute('theme')||'inherit';if(t!=='inherit'&&t!=='auto')return THEMES_SET.has(t)?t:'cyan';const inherited=document.documentElement.dataset.freevTheme||'cyan';return THEMES_SET.has(inherited)?inherited:'cyan'}
function effectiveMode(el){const m=el.getAttribute('mode')||'auto';const safe=MODES.has(m)?m:'auto';if(safe!=='auto')return safe;return matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'}
function effectiveState(el){const s=el.getAttribute('state')||'default';return STATES.has(s)?s:'default'}
function effectiveBadge(el){const b=el.getAttribute('badge')||'none';return BADGES.has(b)?b:'none'}
function effectiveMotion(el){const m=el.getAttribute('motion')||'auto';return MOTIONS.has(m)?m:'auto'}
function effectiveAnimation(el,app,state){let anim=el.getAttribute('animation')||'none';if(!ANIMATIONS.has(anim))anim='none';if(state==='loading'&&(anim==='none'||anim==='auto'))anim=DEFAULT_ANIM[app]||'glow-code';else if(anim==='auto')anim=DEFAULT_ANIM[app]||'none';if(!motionEnabled(el))anim='none';return anim}
const ICON_VARIANTS=new Set(['standard','glass','transparent','monochrome-white','monochrome-black','monochrome-brand','small-simplified']);
function effectiveVariant(el){const v=el.getAttribute('variant')||el.getAttribute('icon-style');return v&&ICON_VARIANTS.has(v)?v:'standard'}
function effectiveSize(el){const raw=Number(el.getAttribute('size')??128);return Number.isFinite(raw)&&raw>0?Math.max(12,Math.min(2048,raw)):128}
function motionEnabled(el){const m=effectiveMotion(el);if(m==='on')return true;if(m==='off')return false;return !matchMedia('(prefers-reduced-motion: reduce)').matches}
const BADGE_A11Y={new:'nouveau',update:'mise à jour',beta:'bêta',pro:'pro',notification:'notification',download:'téléchargement'};
function setA11y(el,app,state,badge='none'){if(el.hasAttribute('decorative')){el.setAttribute('aria-hidden','true');el.removeAttribute('role');el.removeAttribute('aria-label');el.removeAttribute('tabindex')}else{const interactive=el.hasAttribute('interactive');el.setAttribute('role',interactive?'button':'img');const base=el.getAttribute('label')||LABELS[app]||app;el.setAttribute('aria-label',badge!=='none'&&BADGE_A11Y[badge]?`${base}, ${BADGE_A11Y[badge]}`:base);el.removeAttribute('aria-hidden');if(interactive)el.setAttribute('tabindex',state==='disabled'?'-1':'0');else el.removeAttribute('tabindex')}if(state==='disabled')el.setAttribute('aria-disabled','true');else el.removeAttribute('aria-disabled');if(state==='loading')el.setAttribute('aria-busy','true');else el.removeAttribute('aria-busy')}
function escMask(url){return `url(${encodeURI(url).replaceAll(')','%29')}) center/contain no-repeat`}
const HTMLElementBase=globalThis.HTMLElement||class {};
class FreevIcon extends HTMLElementBase{
 static observedAttributes=['app','theme','mode','variant','icon-style','state','badge','size','animation','label','decorative','asset-base','motion','interactive'];
 constructor(){super();this.attachShadow?.({mode:'open'});this._observer=null;this._mq=null;this._motionMq=null;this._onKey=e=>{if(!this.hasAttribute('interactive')||this.getAttribute('state')==='disabled')return;if(e.key==='Enter'||e.key===' '){e.preventDefault();this.click()}};this._onClick=e=>{if(this.getAttribute('state')==='disabled'){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();return}if(this.hasAttribute('interactive'))this.dispatchEvent(new CustomEvent('freev-activate',{bubbles:true,composed:true,detail:{app:this.getAttribute('app')}}))}}
 connectedCallback(){this._watch();this.addEventListener('keydown',this._onKey);this.addEventListener('click',this._onClick,true);this.render()}
 disconnectedCallback(){this._observer?.disconnect();this._mq?.removeEventListener?.('change',this._onScheme);this._motionMq?.removeEventListener?.('change',this._onMotion);this.removeEventListener('keydown',this._onKey);this.removeEventListener('click',this._onClick,true)}
 attributeChangedCallback(){if(this.isConnected)this.render()}
 _watch(){this._observer?.disconnect();this._observer=new MutationObserver(()=>{if(['inherit','auto'].includes(this.getAttribute('theme')||'inherit'))this.render()});this._observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-freev-theme']});this._mq=matchMedia('(prefers-color-scheme: light)');this._onScheme=()=>{if((this.getAttribute('mode')||'auto')==='auto')this.render()};this._mq.addEventListener?.('change',this._onScheme);this._motionMq=matchMedia('(prefers-reduced-motion: reduce)');this._onMotion=()=>{if(effectiveMotion(this)==='auto')this.render()};this._motionMq.addEventListener?.('change',this._onMotion)}
 async render(){
  const app=effectiveApp(this),theme=effectiveTheme(this),mode=effectiveMode(this),variant=effectiveVariant(this),state=effectiveState(this),badge=effectiveBadge(this),size=effectiveSize(this);
  const anim=effectiveAnimation(this,app,state);
  setA11y(this,app,state,badge);this.style.setProperty('--s',size+'px');
  const useSymbol=['transparent','monochrome-white','monochrome-black','monochrome-brand','glass','small-simplified'].includes(variant)||size<=32;
  const master=assetUrl(this,`masters/clean/${app}.png`,app),sym=assetUrl(this,`symbols/mask/${app}.png`,app),smallSym=assetUrl(this,`symbols/small-mask/${app}.png`,app),cover=ANIM_COVER[app]?assetUrl(this,`symbols/animation-cover/${app}.png`,app):null;
  const [dark,light]=THEMES[theme]||THEMES.cyan;const specialMask=(variant==='small-simplified'||size<=32)?smallSym:sym;const maskCss=escMask(specialMask);const coverCss=cover?escMask(cover):'none';
  const layerCount=ANIM_LAYERS[app]||1;const layerMasks=Array.from({length:layerCount},(_,i)=>escMask(assetUrl(this,`symbols/animation-layers/${app}/layer-${i+1}.png`,app)));
  const wholeReconstruct=useSymbol&&RECONSTRUCT_SYMBOL.has(app)&&anim!=='none';
  const symColor=variant==='monochrome-white'?'white':variant==='monochrome-black'?'black':variant==='glass'?'white':light;
  const coverColor=mode==='light'?'#ffffff':'#f7fbff';
  const smallBadge=size<=32&&badge!=='none';const badgeText=smallBadge?'':(BADGE[badge]||'');
  const layerMarkup=anim==='none'?'':layerMasks.map((m,i)=>`<span class="animpart anim-${anim} layer-${i+1}" style="--anim-mask:${m};--layer:${i+1};--anim-color:${symColor}"></span>`).join('');
  const coverMarkup=(!useSymbol&&cover&&anim!=='none')?`<span class="animcover" style="--cover-mask:${coverCss};--cover-color:${coverColor}"></span>`:'';
  let mainMarkup;
  if(variant==='glass')mainMarkup=`<span class="glass"></span>${wholeReconstruct?'':`<span class="symbol" style="--symbol-color:white;--symbol-mask:${maskCss}"></span>`}<span class="accent"></span>`;
  else if(variant==='small-simplified'||size<=32)mainMarkup=`<span class="smallbg"></span>${wholeReconstruct?'':`<span class="symbol" style="--symbol-color:white;--symbol-mask:${maskCss}"></span>`}`;
  else if(useSymbol)mainMarkup=wholeReconstruct?'':`<span class="symbol" style="--symbol-color:${symColor};--symbol-mask:${maskCss}"></span>`;
  else mainMarkup=`<canvas width="${Math.max(64,Math.min(maxRenderSide(),Math.ceil(size*deviceScale())))}" height="${Math.max(64,Math.min(maxRenderSide(),Math.ceil(size*deviceScale())))}"></canvas>`;
  this.shadowRoot.innerHTML=`<style>
 :host{display:inline-block;width:var(--s);height:var(--s);vertical-align:middle;contain:layout paint style;border-radius:22%}:host([interactive]){cursor:pointer}:host([state=disabled]){cursor:not-allowed;user-select:none}:host([interactive]:focus-visible){outline:3px solid ${light};outline-offset:4px}.w{display:block;position:relative;width:100%;height:100%;transition:transform .22s ease,filter .22s ease,opacity .22s ease;transform-origin:center}canvas{display:block;width:100%;height:100%}.glass{position:absolute;inset:0;border-radius:22%;background:linear-gradient(135deg,${dark}80,${light}50);border:1px solid #ffffff55;box-shadow:inset 0 1px 0 #ffffff66,0 14px 28px #0005;backdrop-filter:blur(18px) saturate(1.35)}.glass:before{content:'';position:absolute;left:15%;top:19%;width:64%;height:62%;border-radius:24%;background:#ffffff35;border:1px solid #ffffff55}.symbol{position:absolute;inset:0;background:var(--symbol-color,white);mask:var(--symbol-mask);-webkit-mask:var(--symbol-mask)}.smallbg{position:absolute;inset:0;border-radius:24%;background:linear-gradient(135deg,${dark},${light})}.accent{position:absolute;right:10%;top:47%;width:22%;height:10%;border-radius:999px;background:${light};box-shadow:0 5px 14px #0004}.accent:after{content:'';position:absolute;width:24%;aspect-ratio:1;border-radius:50%;background:white;left:59%;top:50%;transform:translate(-50%,-50%)}
 .animcover,.animpart{position:absolute;inset:0;pointer-events:none}.animcover{background:var(--cover-color);mask:var(--cover-mask);-webkit-mask:var(--cover-mask)}.animpart{background:var(--anim-color,${light});mask:var(--anim-mask);-webkit-mask:var(--anim-mask);transform-origin:center;opacity:${useSymbol?1:.38}}
 .badge{position:absolute;right:-2%;top:-2%;min-width:20%;height:20%;padding:0 5%;display:flex;align-items:center;justify-content:center;border-radius:999px;background:#2F7BFF;color:white;border:max(2px,calc(var(--s)*.012)) solid white;box-sizing:border-box;font:800 max(8px,calc(var(--s)*.075))/1 system-ui;box-shadow:0 5px 14px #0005}.badge.small-badge{right:-3%;top:-3%;width:28%;min-width:28%;height:28%;padding:0;font-size:0;border-width:1px}.badge.small-badge:after{content:'';width:34%;height:34%;border-radius:50%;background:white}.badge[hidden]{display:none}:host([badge=new]) .badge{background:#13C97B}:host([badge=beta]) .badge{background:#9A53FF}:host([badge=pro]) .badge{background:#E0A800}:host([badge=download]) .badge{background:#17B9C8}:host([badge=notification]) .badge{background:#FF4B5C;min-width:16%;width:16%;padding:0;font-size:0}:host([badge=notification]) .badge:after{content:'';width:35%;height:35%;border-radius:50%;background:white}
 :host([state=hover]) .w,:host([interactive]:not([state=disabled]):hover) .w{transform:scale(1.045);filter:brightness(1.10)}:host([state=active]) .w,:host([interactive]:not([state=disabled]):active) .w{transform:scale(.975);filter:brightness(1.12) contrast(1.04)}:host([state=disabled]) .w{opacity:.42;filter:grayscale(.85)}
 @keyframes glowCode{50%{opacity:.72;filter:drop-shadow(0 0 17px ${light})}}@keyframes pulsePlay{50%{transform:scale(1.10);opacity:.98;filter:drop-shadow(0 0 10px ${light})}}@keyframes flowCards{0%,100%{opacity:.22;filter:brightness(1)}50%{opacity:.85;filter:brightness(1.45)}}@keyframes drawPencil{0%,10%{clip-path:inset(82% 0 0 0);opacity:.7}65%,100%{clip-path:inset(0 0 0 0);opacity:1}}@keyframes lockVault{to{transform:rotate(360deg)}}@keyframes convertTop{0%,100%{transform:translateX(-2%);opacity:.82}50%{transform:translateX(3%);opacity:1}}@keyframes convertBottom{0%,100%{transform:translateX(2%);opacity:.82}50%{transform:translateX(-3%);opacity:1}}@keyframes pixelA{0%,100%{opacity:.18}50%{opacity:1;filter:brightness(1.55)}}@keyframes pixelB{0%,100%{opacity:1}50%{opacity:.18}}@keyframes resumeReveal{0%,12%{clip-path:inset(0 100% 0 0);opacity:.55}72%,100%{clip-path:inset(0 0 0 0);opacity:1}}
 .anim-glow-code{animation:glowCode 1.5s ease-in-out infinite}.anim-pulse-play{animation:pulsePlay 1.35s ease-in-out infinite;transform-origin:44.5% 54.5%}.anim-flow-cards.layer-1{animation:flowCards 1.65s ease-in-out infinite}.anim-flow-cards.layer-2{animation:flowCards 1.65s .22s ease-in-out infinite}.anim-flow-cards.layer-3{animation:flowCards 1.65s .44s ease-in-out infinite}.anim-draw-pencil{animation:drawPencil 1.65s ease-in-out infinite}.anim-lock-vault{animation:lockVault 2.2s linear infinite;transform-origin:50.5% 50.8%}.anim-convert-swap.layer-1{animation:convertTop 1.25s ease-in-out infinite}.anim-convert-swap.layer-2{animation:convertBottom 1.25s ease-in-out infinite}.anim-pixel-spark.layer-1{animation:pixelA 1.1s ease-in-out infinite}.anim-pixel-spark.layer-2{animation:pixelB 1.1s ease-in-out infinite}.anim-resume-reveal{animation:resumeReveal 1.9s ease-in-out infinite}
 @media(prefers-reduced-motion:reduce){:host(:not([motion=on])) .animpart{animation:none!important}:host(:not([motion=on])) .w{transition:none!important}}:host([motion=off]) .animpart{animation:none!important}:host([motion=off]) .w{transition:none!important}@media(prefers-contrast:more){.badge{border-width:3px}.glass{border-width:2px}}
 </style><span class="w">${mainMarkup}${coverMarkup}${layerMarkup}<span class="badge${smallBadge?' small-badge':''}" ${badge==='none'?'hidden':''}>${badgeText}</span></span>`;
  if(!useSymbol){const c=this.shadowRoot.querySelector('canvas'),ctx=c.getContext('2d',{willReadFrequently:true}),key=`${master}|${theme}|${mode}|${c.width}x${c.height}`;const cached=renderCache.get(key);if(cached){ctx.drawImage(cached.canvas,0,0,c.width,c.height);renderCache.delete(key);renderCache.set(key,cached)}else{try{const im=await loadImage(master);ctx.drawImage(im,0,0,c.width,c.height);let data=ctx.getImageData(0,0,c.width,c.height);ctx.putImageData(recolor(data,theme),0,0);if(mode==='light'){ctx.globalCompositeOperation='screen';ctx.fillStyle='rgba(255,255,255,.075)';ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='source-over'}const off=document.createElement('canvas');off.width=c.width;off.height=c.height;off.getContext('2d').drawImage(c,0,0);cacheSet(key,off)}catch(error){this.dispatchEvent(new CustomEvent('freev-icon-error',{bubbles:true,composed:true,detail:{app,error}}));ctx.clearRect(0,0,c.width,c.height)}}}
 }
}
if(globalThis.customElements&&!customElements.get('freev-icon'))customElements.define('freev-icon',FreevIcon);
export {FreevIcon,THEMES,APP_REGISTRY,clearFreevIconCaches,getFreevIconCacheStats};
